<a href="https://colab.research.google.com/github/SUYAMBULAKSHMI-VENKATESAN/DAMAKA/blob/main/numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#before using libraries , lib has to be created first, for that in cmd prompt , pip install numpy , it will install, then come back to the code page give command as import numpy
#json - dictionary format - java script


import numpy as np#for data cleaning process - if not - accuracy less - process numerical data - list[any data type] - allow homogenious only(numpy - low memory usage )- allows hetterogenous(list)(high memory usage) - c, c++
import pandas as pd#for data cleaning process - if not - accuracy less - dataframe (forms columns)
import matplotlib #visualization
import sklearn #tensorflow


#numpy in n-dimentional array

# 0 dimentio - single value array
# 1 dim - more than one
# 2 dim - [[ ],[ ]] list kula list

In [3]:
np.array(20) #zero dimentional

array(20)

In [4]:
np.array([4,7,8,14,20]) #one dimentional array

array([ 4,  7,  8, 14, 20])

In [44]:
a=np.array([[1,2,3],[4,5,6]]) #two dimentional array
b=np.array([[10,20,30],[40,50,60]])

In [7]:
# if i wanna convert this 2 dimentional array into 3 dimentional array
np.array([[1,2,3],[4,5,6]]) #no of square bracket = no of dimentional array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.ndim


2

In [10]:
a.shape

(2, 3)

In [11]:
a.size

6

In [12]:
#hands on

array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

print("ARITHMETIC OPERATIONS")

print("ADDITION = ", array1 + array2)
print("SUBTRACTION = ", array1 - array2)
print("MULTIPLICATION = ", array1 * array2)
print("DIVISION = ", array1 / array2)

ARITHMETIC OPERATIONS
ADDITION =  [ 7  9 11 13 15]
SUBTRACTION =  [-5 -5 -5 -5 -5]
MULTIPLICATION =  [ 6 14 24 36 50]
DIVISION =  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [16]:
np.max(array1)

5

In [17]:
np.min(array2)

6

In [18]:
np.std(array1)

1.4142135623730951

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.arange(0,20,3) #start,stop,step size

array([ 0,  3,  6,  9, 12, 15, 18])

In [27]:
np.random.random(10000) #it keeps on changes the values - will not able to see the same value

array([0.11545639, 0.60813934, 0.36790418, ..., 0.078596  , 0.64888643,
       0.34400714])

In [29]:
np.random.randint(10000,28465849,5) #going to generate a random integer

array([26788830, 14216870, 22676564, 25336961,  8100724])

In [36]:
np.concatenate((array1,array2), axis=0) #concatenate in row for axis = 0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.concatenate((a,b), axis=1) #concatenate in column (vertical) for axis = 1

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [40]:
#vertical stack
np.vstack([array1,array2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
#horizontal stack
np.hstack([array1,array2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
#indexing starts with 0 .... to right(+ve), -1......left(-ve)
a=np.array([[1,2,3],[4,5,6]]) #two dimentional array
b=np.array([[10,20,30],[40,50,60]])
b[1][1]  #here selecting 1 order lists 1 order element

50

In [48]:
od=np.array([1,2,3,4,5,6])
od.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ravel()

In [50]:
#slicing

od[2:4]

array([3, 4])

In [55]:
od = np.array([1, 2, 3, 4, 5, 6], dtype="bool")
print(od)

[ True  True  True  True  True  True]
